# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2020-03-13 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patients',
            table='patients',
        ),
    ]
