# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2020-03-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20200313_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='telephone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
